server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  main:
    allow-circular-references: true
  profiles:
    include:
    - oauth2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hts?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: htsDev
    password: htsDev1234!
   
  jpa:
    hibernate:
      ddl-auto: update # create update 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 268784453261-0hq5v9oda6d10utvnn6p64o4oc08f7q9.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          
          naver:
            client-id: PyQIvEf3Sk6GPWt4reQn
            client-secret: GMAJPPUqzw
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oatuth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        
mybatis:
  configuration:
      multiple-result-sets-enabled: false    
      map-underscore-to-camel-case: true    
      call-setters-on-nulls: true        
      jdbc-type-for-null: varchar    
      default-fetch-size: 500  
      
logging:
  level: 
    root: debug
      

          
          
    